const MEMBERS=[["최애리", "CHOI ERI", "🍒", "#AB3E1A", "#D2B595"], ["눈요", "NUNYO", "❄️🐇", "#F0FDFC", "#77A0FD"], ["여우연", "YEO WOOYEON", "💎🦊", "#C9DFEA", "#F0F8FD"], ["설홍", "SEOLHONG", "🌺", "#B64659", "#FF92A7"], ["나노", "NANO", "✖️🖤", "#E06064", "#373543"], ["루첼", "RUCHEL", "💀🍓", "#A3233E", "#272332"]];
const ITEMS=[{"cat": "species", "title": "설표 루첼", "src": "images/ruchel/species/01.webp", "memo": "설원에서도 새침한 건 그대로.", "date": "2026.09.11"}, {"cat": "species", "title": "브라키오사우르스 루첼", "src": "images/ruchel/species/02.webp", "memo": "목이 길어져도 루첼은 루첼.", "date": "2026.09.11"}, {"cat": "species", "title": "햄스터 루첼", "src": "images/ruchel/species/03.webp", "memo": "작고 말랑한 부족장님.", "date": "2026.09.11"}, {"cat": "species", "title": "고양이 루첼", "src": "images/ruchel/species/04.webp", "memo": "사랑받는 게 당연한 고양이.", "date": "2026.09.11"}, {"cat": "species", "title": "루돌프 루첼", "src": "images/ruchel/species/05.webp", "memo": "올겨울도 길 잃을 걱정은 없겠다.", "date": "2026.09.11"}, {"cat": "jobs", "title": "골골이호 선장 루첼", "src": "images/ruchel/jobs/01.webp", "memo": "오늘도 골골이호는 순항 중.", "date": "2026.09.11"}, {"cat": "jobs", "title": "해군제독 루첼", "src": "images/ruchel/jobs/02.webp", "memo": "작아도 계급은 제독입니다.", "date": "2026.09.11"}, {"cat": "jobs", "title": "골골이호 선원 루첼", "src": "images/ruchel/jobs/03.webp", "memo": "오늘도 출항 준비 완료.", "date": "2026.09.11"}, {"cat": "jobs", "title": "무희 루첼", "src": "images/ruchel/jobs/04.webp", "memo": "한 번쯤 보고 싶었던 무대 위 루첼.", "date": "2026.09.11"}, {"cat": "jobs", "title": "루첼모음", "src": "images/ruchel/jobs/05.webp", "memo": "한 장에 모아둔 여러 모습의 루첼.", "date": "2026.09.11"}, {"cat": "anniversary", "title": "1주년 메이드 카페", "src": "images/ruchel/maid-cafe.webp", "memo": "처음으로 직접 보러 갔던 날.", "date": "2026.09"}];

const CATS=[['ruchel','💀🍓','RUCHEL','루첼'],['species','🐾','RACES & FORMS','종족'],['jobs','⚓','JOBS & ROLES','직업'],['fantasy','🔮','FANTASY','판타지'],['outfit','👗','OUTFITS','의상'],['anniversary','🎂','ANNIVERSARY','기념일'],['broadcast','🎮','STREAM & GAME','방송 & 게임'],['special','✦','SPECIAL','스페셜']];
const albums=document.querySelector('#albums'); MEMBERS.forEach((m,i)=>{let d=document.createElement('article');d.className='album '+(i===5?'open':'');d.style.setProperty('--p',m[3]);d.style.setProperty('--s',m[4]);d.innerHTML=`<span class=num>0${i+1}</span><div class=mark>${m[2]}</div><h3>${m[0]}</h3><em>${m[1]}</em><div class=state>${i===5?'OPEN ARCHIVE':'ARCHIVE PREPARING...'}</div>`;if(i===5)d.onclick=openR;albums.append(d)});
function openR(){transition.style.display='grid';setTimeout(()=>{transition.style.display='none';archive.classList.remove('active');member.classList.add('active');scrollTo(0,0)},1350)}
back.onclick=()=>{member.classList.remove('active');archive.classList.add('active');content.hidden=true;scrollTo(0,0)};enter.onclick=()=>{content.hidden=false;content.scrollIntoView({behavior:'smooth'})};
CATS.forEach(c=>{let n=ITEMS.filter(x=>x.cat===c[0]).length,d=document.createElement('button');d.className='cat';d.innerHTML=`<i>${c[1]}</i><b>${c[3]}</b><small>${c[2]}</small><span>${n} ${n===1?'MEMORY':'MEMORIES'}</span>`;d.onclick=()=>render(c);cats.append(d)});
function render(c){title.textContent=c[3];kick.textContent=c[2];let a=ITEMS.filter(x=>x.cat===c[0]);count.textContent=`${a.length} ${a.length===1?'memory':'memories'}`;photos.innerHTML='';if(!a.length){photos.innerHTML='<div class="empty">아직 기록되지 않은 페이지.<br><small>이미지가 추가되면 이곳에 차곡차곡 쌓입니다.</small></div>';return}a.forEach((x,i)=>{let d=document.createElement('article');d.className='memory m'+(i%5);d.innerHTML=`<img loading="lazy" src="${x.src}"><h4>${x.title}</h4><p>${x.memo}</p><time>${x.date}</time>`;d.onclick=()=>show(x);photos.append(d)});document.querySelector('.ghead').scrollIntoView({behavior:'smooth'})}
function show(x){lbimg.src=x.src;lbdate.textContent=x.date;lbtitle.textContent=x.title;lbmemo.textContent=x.memo;lightbox.classList.add('show')}close.onclick=()=>lightbox.classList.remove('show');lightbox.onclick=e=>{if(e.target===lightbox)lightbox.classList.remove('show')};render(CATS[1]);
